### ISSUE TITLE
Templates Theme

### ISSUE THREAD

**Issue by mfikrigunawan** [OkularID/RSTemplates#94]
###	Wedding
- [x] dylan_rose
- [x] emma_norman
- [x] jack_jane
- [x] liam_felicia
- [x] lucas_eli
- [x] natasha_bruce
- [x] peter_mary
- [x] steve_sharon
- [x] vicky_wanda
- [x] victor_karla

## Birthday
- [x] aaron
- [x] anastasia
- [x] christine
- [x] diana_ross

## Event
- [x] 10year_reunion
- [x] 20year_reunion
- [x] brotherfield
- [x] christmas_dinner
- [x] lacasadepapel
- [x] music
- [x] oceandor
- [x] seminary

## Free
- [x] anastasia
- [x] christine
- [x] diana_ross
- [x] dylan_rose
- [x] natasha_bruce
- [x] steve_sharon

**Comment by iColdPlayer** [comment]
done & fixed
